2022-10-12 22:50:50,848 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-36be52ed8dd2830c1c2064a82ff07a81
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7ffbaf74eb90>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:50,916 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-a4e26ab8b4155bf0a996b9f1e341f126
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f4758a1eb00>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,066 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-14eb5c800d6995a2559f165745c0612b
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7efff9fa2aa0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,387 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-89cd66b537ea30a63f7d350c57ad5ed1
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f629316ab90>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,422 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-d69d357074f306cf0c147ec31ece43cc
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f4a7a516b00>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,447 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-a8c366bfc025b9ea2b974de3c4498175
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fd33cf06830>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,558 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-ecd8c30624fb470d7331501ffb96716d
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fbf6dee6ef0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,596 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-b317dbb5cb5177aae396126a5c4b6fa2
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f150b422ad0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,662 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-dc9b3d22e5c8573d90f003ad980a2bb3
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7efe767c6ad0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,672 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-c2cbcec46ff9246a3d8e22684f8446d4
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f362877e650>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,683 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-0d8067966e0c2a4ca6353f5f5c0a45d5
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7ffac5add930>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,720 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-ea5d56ca150ec84ad27ee3cb2114929b
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f2e236eaec0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,741 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-60711f1649369d55e713c8246c18726c
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f2ad4316320>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,770 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-a586c1065a775b821ac3e34c0c552873
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7febfbf32b60>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:51,775 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-c7e9bc5b65e688d9d99a210b77d1df29
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f46838cabc0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,090 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-c6663c7d6e3c9ea4a8c623a456af7ec0
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f72991beec0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,121 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-6bb69fddd636d12f86183346f243553a
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fb58e0feb00>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,135 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-db16f7308c112e7483870e24770ca11b
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f180709af20>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,156 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-31319c1ca8092c3f8ae1d5de49ce850a
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f6254b4a5c0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,180 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-50e279f072b0595e8aa46d4e01c43276
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f582557dd50>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,233 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-86d65c2da745e693f0f4bbabb2ad08f4
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f7699ec2ef0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,247 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-37453ec5ba0e02886b0e49d124fc583d
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fde4667aad0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,248 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-01061825767d028dc7d3e0723f8dda90
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7febb216e050>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,282 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-f0a2d450f6fe066fe7e8b8815e69c6b8
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f899afdab90>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,285 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-8afd522247e60cb79296f258d3e04d99
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f0d97dfe8f0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,317 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-33d835d9c49ac919d0670c641167fb18
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f7a04e86350>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,329 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-3843ae6dc52fc1398a8e4b045bc197b2
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fc39c14eb60>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,474 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-59db4adafcc626f109f4bbb68734f554
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7fe18322a770>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,484 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-332c59a83699348c5e10d6c90abb7af6
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7ff4ba2e6b90>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,521 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-c40ce376f1e8c19d097e81b44b1d03b1
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f4b4b20eb30>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,549 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-573f58af26cd2e6663aafed8eaec5d48
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f2bd148aef0>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

2022-10-12 22:50:52,562 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-6562e6e728387528fdc8d50f91cce458
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f7a73056590>)
kwargs:    {}
Exception: "DataError('No numeric types to aggregate')"

Distributing data time: 0.9622993469238281
Execution time: 6.780496597290039
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 404, in _prep_values
    values = ensure_float64(values)
  File "pandas/_libs/algos_common_helper.pxi", line 42, in pandas._libs.algos.ensure_float64
ValueError: could not convert string to float: 'SEVERE WINTER STORM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 483, in _apply_series
    values = self._prep_values(obj._values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 406, in _prep_values
    raise TypeError(f"cannot handle this type -> {values.dtype}") from err
TypeError: cannot handle this type -> object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/forms/benchmark/test_driver.py", line 50, in <module>
    result = fs.compute_formula(df, formula_str)
  File "/home/ubuntu/forms/forms/core/forms.py", line 44, in compute_formula
    res = plan_executor.df_execute_formula_plan(df, root)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 81, in df_execute_formula_plan
    return res_table.get_table_content()
  File "/home/ubuntu/forms/forms/executor/table.py", line 55, in get_table_content
    self.df = self.remote_df.get_df_content()
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 80, in get_df_content
    [
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/runtime/remoteobject.py", line 33, in get_computed_result
    return self.object_ref.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/distributed/client.py", line 277, in result
    raise exc.with_traceback(tb)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 45, in execute_one_subtree
    res_table = function_executor(physical_subtree)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/basicfuncexecutor.py", line 116, in sum_df_executor
    return distributive_function_executor(physical_subtree, Function.SUM)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/basicfuncexecutor.py", line 320, in distributive_function_executor
    value = get_value_rr(
  File "/home/ubuntu/forms/forms/executor/dfexecutor/utils.py", line 226, in get_value_rr
    df.agg(func1, axis=1).rolling(window_size, min_periods=window_size).agg(func2).dropna()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 1921, in aggregate
    return super().aggregate(func, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 709, in aggregate
    result = ResamplerWindowApply(self, func, args=args, kwargs=kwargs).agg()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/apply.py", line 177, in agg
    return getattr(obj, f)()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 2084, in sum
    return super().sum(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 1476, in sum
    return self._apply(window_func, name="sum", numeric_only=numeric_only, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 663, in _apply
    return self._apply_blockwise(homogeneous_func, name, numeric_only)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 503, in _apply_blockwise
    return self._apply_series(homogeneous_func, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/window/rolling.py", line 485, in _apply_series
    raise DataError("No numeric types to aggregate") from err
pandas.errors.DataError: No numeric types to aggregate
